[package]
name = "migrator"
version = "0.1.0"
edition = "2024"

[lib]
name = "migrator"
path = "src/lib.rs"

[[bin]]
name = "migrator"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "0.33.0", features = ["bundled"] }
